version: '3'

services:
  frontend:  # React用のコンテナ
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: front
    tty: true
    volumes:
      - ./frontend:/frontend
    working_dir: "/frontend"
    ports:
      - 3001:3000
  backend:  # Express用のコンテナ
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: back
    tty: true
    volumes:
      - ./backend:/backend
      - ./docker/backend/.aws:/root/.aws
    working_dir: "/backend"
    ports:
      - 3002:3000
    networks:
      - dynamodb-local-network
  dynamodb-local:
    build:
      context: .
      dockerfile: ./docker/dynamodb-local/Dockerfile
    container_name: dynamodb-local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-local-data:/data
    ports:
      - 8000:8000
    networks:
      - dynamodb-local-network
  dynamodb-admin:
    build:
      context: .
      dockerfile: ./docker/dynamodb-admin/Dockerfile
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network

volumes:
  dynamodb-local-data:

networks:
  dynamodb-local-network:
    driver: bridge

