swagger: "2.0"
info:
  description: "ToDo アプリケーション REST API ドキュメント"
  version: "1.0.0"
  title: "ToDo Rest API Docment"
host: "af0czrklbb.execute-api.ap-northeast-3.amazonaws.com"
basePath: "/v1"
tags:
- name: "task"
  description: "タスク情報の取得・更新"
schemes:
- "https"
paths:
  /tasks:
    get:
      tags:
      - "task"
      summary: "タスクの取得"
      description: "全てのタスク情報を取得します"
      operationId: "getTasks"
      produces:
      - "application/json"
      # TODO: 受け付けるクエリパラメータを全部書く
      parameters:
      - name: "State"
        in: "query"
        type: "string"
        default: "new"
        enum:
        - "new"
        - "progress"
        - "done"
        description: "タスクの状態"
      - name: "lastState"
        in: "query"
        type: "string"
        description: "ページングを行う際に2ページ目以降を取得するための情報。lastId, lastCreatedAt と3つ合わせてリクエストを送る必要がある"
      - name: "lastId"
        in: "query"
        type: "string"
        description: "ページングを行う際に2ページ目以降を取得するための情報。lastState, lastCreatedAt と3つ合わせてリクエストを送る必要がある"
      - name: "lastCreatedAt"
        in: "query"
        type: "string"
        description: "ページングを行う際に2ページ目以降を取得するための情報。lastState, lastId と3つ合わせてリクエストを送る必要がある"
      - name: "titleQuery"
        in: "query"
        type: "string"
        description: "タイトルの部分一致で検索を行う"
      - name: "limit"
        in: "query"
        type: "number"
        default: 10
        description: "取得する最大件数を指定する。大きくしすぎるとレスポンスが返ってこないため注意が必要。"

      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            properties:
              Items:
                type: "array"
                items:
                  $ref: "#/definitions/Task"
              Count:
                type: "number"
                example: 1
              ScannedCount:
                type: "number"
                example: 1
              LastEvaluatedKey:
                type: "object"
                properties:
                  State:
                    type: "string"
                    example: "new"
                  Id:
                    type: "string"
                    example: "9aiIoA_kMDIGa1ixG2ewG"
                  CreatedAt:
                    type: "string"
                    example: "2022-03-29_13:12:38"


        "400":
          description: "リクエストパラメータが不正な値です"
    post:
      tags:
      - "task"
      summary: "タスクの追加"
      description: ""
      operationId: "createTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          type: "object"
          properties:
            title:
              type: "string"
            content:
              type: "string"
            limit:
              type: "string"
            state:
              type: "string"
              enum:
              - "new"
              - "progress"
              - "done"
      responses:
        "200":
          description: "タスクの作成に成功。空のオブジェクト {} が返却されます"
        "400":
          description: "リクエストパラメータに誤りがあります"
        "404":
          description: "指定されたIDのタスクが見つかりません"
  /tasks/{id}:
    put:
      tags:
      - "task"
      summary: "タスクの更新"
      description: ""
      operationId: "updateTask"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      - name: "body"
        in: "body"
        description: "タスクの情報を全てボディに含めてください"
        required: true
        schema:
          $ref: "#/definitions/Task"
      responses:
        "200":
          description: "更新成功。更新したデータが返却されます"
        "400":
          description: "リクエストパラメータに誤りがあります"
        "404":
          description: "指定されたIDのタスクが見つかりません"
    delete:
      tags:
      - "task"
      summary: "タスクの削除"
      description: ""
      operationId: "deleteTask"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "削除するタスクのID"
        required: true
        type: "string"
      responses:
        "404":
          description: "指定されたIDのタスクが見つかりません"
definitions:
  Task:
    type: "object"
    required:
    - "Title"
    - "Content"
    - "Limit"
    - "State"
    properties:
      Id:
        type: "string"
        format: "21 symbols [A-Za-z0-9_-]"
        description: "作成時に自動で割り振られます"
        example: "9aiIoA_kMDIGa1ixG2ewG"
      Title:
        type: "string"
      Content:
        type: "string"
      Limit:
        type: "string"
        format: "YYYY-DD-MM"
      State:
        type: "string"
        enum:
        - "new"
        - "progress"
        - "done"
      CreatedAt:
        type: "string"
        format: "YYYY-MM-DD_HH:mm:ss"
